const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const ctx={document:{createElement:()=>({}),head:{appendChild(){}}},state:{profile:{role:'super_admin'}}};
ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../tax-inventory.js'),'utf8'),ctx);
const plain=x=>JSON.parse(JSON.stringify(x));
const parse=x=>plain(ctx.parseTaxCodes(x));
assert.deepEqual(parse('SKU,group/set,note\r\n001,Set A,"comma, and ""quote"""'),[{code:'001',tax_group_or_set:'Set A',tax_note:'comma, and "quote"'}]);
assert.deepEqual(parse('\uFEFFSKU\n A \n\nB'),[{code:'A'},{code:'B'}]);
assert.deepEqual(parse('SKU\tgroup\tnote\nA\t\tline'),[{code:'A',tax_group_or_set:null,tax_note:'line'}]);
assert.equal(parse('A,G,"line 1\nline 2"')[0].tax_note,'line 1\nline 2');
assert.throws(()=>parse('A,"unfinished'),/Unclosed/);
assert.throws(()=>parse('A,B,C,D'),/expected SKU/);
assert.throws(()=>parse(Array(501).fill('A').join('\n')),/500/);
assert.throws(()=>parse('A,'+'x'.repeat(201)),/too long/);
const products=[{id:'1',code:'A',tax_item:true},{id:'2',code:'B'},{id:'3',code:'b'}];
const matches=plain(ctx.matchTaxCodes([{code:' a '},{code:'B'},{code:'NONE'},{code:'C'},{code:'c'}],products));
assert.deepEqual(matches.map(r=>r.status),['Matched','Ambiguous code','Unmatched','Duplicate input','Duplicate input']);
assert.equal(matches[0].product.id,'1');
assert.equal(ctx.taxBadge({tax_item:false}),'');
assert.match(ctx.taxBadge({tax_item:true}),/TAX/);
(async()=>{
  const fixture=Array.from({length:1690},(_,id)=>({id}));let requests=0;
  ctx.db={from:()=>({select:()=>({order:()=>({range:async(a,b)=>{requests++;return {data:fixture.slice(a,b+1)}}})})})};
  assert.equal((await ctx.taxFetchAll('fixture')).length,1690);assert.equal(requests,2);
  ctx.db.rpc=()=>({order:()=>({range:async(a,b)=>({data:fixture.slice(a,b+1)})})});
  assert.equal((await ctx.taxFetchAll('aging','*','product_id',true)).length,1690);
  ctx.db={from:()=>({select:()=>({order:()=>({range:async()=>({error:new Error('Read failed')})})})})};
  await assert.rejects(()=>ctx.taxFetchAll('fixture'),/Read failed/);
  console.log('PASS: CSV/TSV quoting, multiline, BOM, leading zeros, empty/omitted columns, limits, ambiguous/duplicate/unmatched codes, badges, complete pagination, read errors.');
})().catch(e=>{console.error(e);process.exitCode=1});
